# https://hub.docker.com/_/orientdb
version: '3.3'
services: 
    db:
        container_name: devorientdb
        image: orientdb:3.2.0
        restart: always
        environment: 
            - 'ORIENTDB_ROOT_PASSWORD=test123'
        ports: 
            - '2424:2424'
            - '2480:2480' 
            # 2480 http client