version: '3.0'
services:
    db:
        container_name: 'devpostgres'
        image: postgres:alpine3.14
        restart: always
        ports:
            - '5432:5432'
        environment:
            - 'POSTGRES_PASSWORD=fifa10'
    client:
        image: dpage/pgadmin4:5
        restart: always
        ports:
            - '5555:80'
        environment: 
            - 'PGADMIN_DEFAULT_EMAIL=test@test.com'
            - 'PGADMIN_DEFAULT_PASSWORD=test123'