version: '3.3'
services: 
    db:
        container_name: devmongodb
        image: mongo:5.0.2
        restart: always
        ports: 
            - '27017:27017'
    client:
        image: mongo-express:latest
        restart: always
        environment: 
            - 'ME_CONFIG_MONGODB_SERVER=devmongodb'
            - 'ME_CONFIG_BASICAUTH_USERNAME=test'
            - 'ME_CONFIG_BASICAUTH_PASSWORD=test123'
        ports: 
            - '27018:8081'
        depends_on: 
            - db
